services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - target: 3306
        published: 3307
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: